events {
    worker_connections 1024;
}

http {
    upstream ms-clients {
        server ms-clients:8082;
    }

    upstream ms-accounts {
        server ms-accounts:8081;
    }

    server {
        listen 80;

        location /clients/ {
            proxy_pass http://ms-clients/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /accounts/ {
            proxy_pass http://ms-accounts/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}